---
- name: "Push local configuration file"
  notify: "(Re)start and enable ipmi_exporter"
  when: ipmi_exp_local_conf_path is defined and ipmi_exp_local_conf_path | length > 0
  ansible.builtin.template:
    src: "{{ ipmi_exp_local_conf_path }}"
    dest: "{{ ipmi_exp_config_dir }}/local.yml"
    owner: root
    group: root
    mode: '0640'

- name: "Push web configuration file"
  notify: "(Re)start and enable ipmi_exporter"
  when: ipmi_exp_web_conf_path is defined and ipmi_exp_web_conf_path | length > 0
  ansible.builtin.template:
    src: "{{ ipmi_exp_web_conf_path }}"
    dest: "{{ ipmi_exp_config_dir }}/web.yml"
    owner: root
    group: root
    mode: '0640'
